### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by albertml** [kazuhiro4949/PagingKit#79]
How to support RTL for the menu? like when arabic, the menu will start at the right.

![screen shot 2018-11-21 at 9 55 46 pm](https://user-images.githubusercontent.com/8196166/48845741-41f38f80-edd8-11e8-839e-d53f9a2d5985.png)

**Comment by kazuhiro4949** [comment]
Hi, @albertml 
I'm sorry it hasn't supported RTL yet. 
I know it's a important feature to UI libraries but I don't have an enough time to support it.

**Comment by kazuhiro4949** [comment]
Hi, @albertml.
CGAffineTransform is a reasonable approach to implement RTL.

This is SampleViewController in sample code.

<img width="559" alt="2018-12-03 22 29 30" src="https://user-images.githubusercontent.com/18320004/49376591-05665300-f74b-11e8-9e2e-c11797c8d116.png">


For example, you can change the scroll direction with the following code.

```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        menuViewController?.menuView.transform = CGAffineTransform(scaleX: -1, y: 1) // <-
        contentViewController?.scrollView.transform = CGAffineTransform(scaleX: -1, y: 1) // <-
    }
```

It's not enough because PagingMenuViewCell and UITableViewCell is transformed too.

<img width="559" alt="2018-12-03 22 26 19" src="https://user-images.githubusercontent.com/18320004/49376416-7f4a0c80-f74a-11e8-8b03-82ef9a96fac2.png">

So you needs to apply transform to them.

```swift
extension SimpleViewController: PagingMenuViewControllerDataSource {
    func menuViewController(viewController: PagingMenuViewController, cellForItemAt index: Int) -> PagingMenuViewCell {
        let cell = viewController.dequeueReusableCell(withReuseIdentifier: "identifier", for: index)  as! TitleLabelMenuViewCell
        cell.transform = CGAffineTransform(scaleX: -1, y: 1)
        cell.titleLabel.text = dataSource[index].menu
        return cell
    }
}
```

```swift
extension SimpleViewController: PagingContentViewControllerDataSource {
    func contentViewController(viewController: PagingContentViewController, viewControllerAt index: Int) -> UIViewController {
        let viewController = dataSource[index].content
        viewController.view.transform = CGAffineTransform(scaleX: -1, y: 1)
        return dataSource[index].content
    }
}
```

Only the menu will start at the right.

<img width="559" alt="2018-12-03 22 22 29" src="https://user-images.githubusercontent.com/18320004/49376432-8cff9200-f74a-11e8-9a66-64e3f1fcbbfd.png">

It's not a feature in PagingKit, but it should be enough.

Thanks.

**Comment by kazuhiro4949** [comment]
I'll close this issue.
